# Generated by Django 4.1.7 on 2023-04-14 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_note', models.TextField()),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('modified_at', django_jalali.db.models.jDateField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start_at', models.DateField()),
                ('duration', models.PositiveSmallIntegerField(default=6)),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=7)),
                ('class_time', models.TimeField()),
                ('how_to_hold', models.CharField(choices=[('Online', 'Online'), ('In person', 'In person')], max_length=15)),
                ('short_brief', models.CharField(max_length=70)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_of_course', to='mentor.mentor')),
            ],
        ),
    ]
