# Generated by Django 4.1.7 on 2023-04-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ceo", "0001_initial"),
        ("mentor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=35)),
                ("last_name", models.CharField(max_length=35)),
                ("phone_number", models.CharField(max_length=13, unique=True)),
                ("date_of_birth", models.DateField()),
                ("identity_code", models.CharField(max_length=15, unique=True)),
                (
                    "personality",
                    models.CharField(
                        choices=[
                            ("INTP", "INTP"),
                            ("INTJ", "INTJ"),
                            ("ENTJ", "ENTJ"),
                            ("ENTP", "ENTP"),
                            ("INFJ", "INFJ"),
                            ("INFP", "INFP"),
                            ("ENFJ", "ENFJ"),
                            ("ENFP", "ENFP"),
                            ("ISTJ", "ISTJ"),
                            ("ISFJ", "ISFJ"),
                            ("ESTJ", "ESTJ"),
                            ("ESFJ", "ESFJ"),
                            ("ISTP", "ISTP"),
                            ("ISFP", "ISFP"),
                            ("ESTP", "ESTP"),
                            ("ESFP", "ESFP"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_course",
                        to="ceo.course",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_payment_due_date", models.BooleanField(default=False)),
                ("new_task", models.BooleanField(default=False)),
                ("new_message", models.BooleanField(default=False)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_text", models.TextField()),
                ("report_number", models.PositiveIntegerField(default=1)),
                ("amount_of_study", models.PositiveIntegerField()),
                ("is_submitted", models.BooleanField(default=True)),
                ("date_of_reporting", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_number", models.IntegerField()),
                ("receipt", models.ImageField(upload_to="receipt_images/")),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=30)),
                ("course_length", models.IntegerField()),
                ("completed", models.IntegerField()),
                (
                    "belong_to",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
                (
                    "mentor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="mentor.mentor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletedCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                ("course_length", models.IntegerField()),
                ("started_at", models.DateField()),
                ("finished_at", models.DateField()),
                (
                    "mentor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="mentor.mentor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_of_receipt", models.CharField(max_length=9)),
                ("receipt_count", models.IntegerField()),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_payments",
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
