# Generated by Django 4.1.7 on 2023-03-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_text', models.TextField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
