# Generated by Django 4.1.7 on 2023-04-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
